version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Deploy Docker Image
          command: kompose up
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
