apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - env:
        - name: SERVER_URL
          value: localhost:3001
        image: gcr.io/osmium/osmium-client
        name: client
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
