name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Client Docker image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: docker build -f ./docker/prod-client.Dockerfile -t gcr.io/$PROJECT_ID/osmium-client:$(git describe --abbrev=0 --tags) .

      - name: Build the Server Docker image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: docker build -f ./docker/prod-server.Dockerfile -t gcr.io/$PROJECT_ID/osmium-server:$(git describe --abbrev=0 --tags) .

      - name: Log in to gcloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker auth
        uses: actions/gcloud/cli@master
        with:
          args: "auth configure-docker --quiet"

      - name: Push the Client Docker image
        uses: actions/gcloud/cli@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          args: "--verbosity=error docker -- push gcr.io/$PROJECT_ID/osmium-client:$(git describe --abbrev=0 --tags)"

      - name: Push the Server Docker image
        uses: actions/gcloud/cli@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          args: "--verbosity=error docker -- push gcr.io/$PROJECT_ID/osmium-server:$(git describe --abbrev=0 --tags)"

      - name: Load GKE kube credentials
        uses: actions/gcloud/cli@master
        env:
          ZONE: ${{ secrets.ZONE }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        with:
          args: "container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID"

      - name: Concat and process kube resources
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: SHORT_REF=$(echo ${GITHUB_REF} | grep -E -o 'v([0-9]\.?)+') && awk 'FNR==1{print "---"}{print}' ./deploy/* | sed '1d' | sed 's/PROJECT_ID/'$PROJECT_ID'/' | sed 's/TAG/'$SHORT_REF'/' > deploy.txt

      - name: Deploy GKE resources
        uses: docker://gcr.io/cloud-builders/kubectl
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.PROJECT_ID }}
          CLOUDSDK_COMPUTE_ZONE: ${{ secrets.ZONE }}
          CLOUDSDK_CONTAINER_CLUSTER: ${{ secrets.CLUSTER_NAME }}
        with:
          args: "apply -f deploy.txt"
