name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Client Docker image
        run: docker build -f ./docker/prod-client.Dockerfile -t gcr.io/osmium-250702/osmium-client:$(git describe --abbrev=0 --tags) .

      - name: Build the Server Docker image
        run: docker build -f ./docker/prod-server.Dockerfile -t gcr.io/osmium-250702/osmium-server:$(git describe --abbrev=0 --tags) .

      - name: Log in to gcloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker auth
        uses: actions/gcloud/cli@master
        with:
          args: "auth configure-docker --quiet"

      - name: Push the Client Docker image
        uses: actions/gcloud/cli@master
        with:
          args: "--verbosity=error docker -- push gcr.io/osmium-250702/osmium-client:$(git describe --abbrev=0 --tags)"

      - name: Push the Server Docker image
        uses: actions/gcloud/cli@master
        with:
          args: "--verbosity=error docker -- push gcr.io/osmium-250702/osmium-server:$(git describe --abbrev=0 --tags)"

      - name: Load GKE kube credentials
        uses: actions/gcloud/cli@master
        with:
          args: "container clusters get-credentials osmium-cluster --zone us-east1-b --project osmium-250702"

      - name: Delete GKE resources
        uses: docker://gcr.io/cloud-builders/kubectl
        env:
          CLOUDSDK_CORE_PROJECT: osmium-250702
          CLOUDSDK_COMPUTE_ZONE: us-east1-b
          CLOUDSDK_CONTAINER_CLUSTER: osmium-cluster
        with:
          args: "delete -f ./deploy"

      - name: Deploye GKE resources
        uses: docker://gcr.io/cloud-builders/kubectl
        env:
          CLOUDSDK_CORE_PROJECT: osmium-250702
          CLOUDSDK_COMPUTE_ZONE: us-east1-b
          CLOUDSDK_CONTAINER_CLUSTER: osmium-cluster
        with:
          args: "create -f ./deploy"
